qlib_init:
    provider_uri: "~/.qlib/qlib_data/tushare_data"
    region: cn
market: &market all
benchmark: &benchmark SH000300
data_handler_config: &data_handler_config
    start_time: 2019-01-01
    end_time: 2025-12-31
    fit_start_time: 2019-01-01
    fit_end_time: 2023-12-31
    instruments: *market
    infer_processors:
        - class: ProcessInf
          kwargs: {}
        - class: RobustZScoreNorm
          kwargs:
              fields_group: feature
              clip_outlier: true
        - class: Fillna
          kwargs:
              fields_group: feature
    learn_processors:
        - class: DropnaLabel
        - class: CSRankNorm
          kwargs:
              fields_group: label
    filter_pipe:
        - filter_type: ExpressionDFilter
          rule_expression: "Abs($close / Ref($close, 1) - 1) < 0.095"
task:
    model:
        class: LGBModel
        module_path: qlib.contrib.model.gbdt
        kwargs:
            loss: mse
            colsample_bytree: 0.8879
            learning_rate: 0.2
            subsample: 0.8789
            lambda_l1: 20
            lambda_l2: 50
            max_depth: 6
            num_leaves: 80
            num_threads: 20
    dataset:
        class: DatasetH
        module_path: qlib.data.dataset
        kwargs:
            handler:
                class: Alpha158
                module_path: qlib.contrib.data.handler
                kwargs: *data_handler_config
            segments:
                train: [2022-01-01, 2024-06-30]
                valid: [2024-07-01, 2024-12-31]
                test:  [2025-01-01, 2025-12-31]
    record: 
        - class: SignalRecord
          module_path: qlib.workflow.record_temp
          kwargs: 
            model: <MODEL>
            dataset: <DATASET>
        - class: SigAnaRecord
          module_path: qlib.workflow.record_temp
          kwargs: 
            ana_long_short: False
            ann_scaler: 252